version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python app.py
    restart: always
    volumes:
      - .:/usr/projects/autopostingbot
    ports:
      - 8000:8000
    env_file:
      - ./config.ini
    depends_on:
      - db
  db:
    image: postgres:13.3
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config.ini
    ports:
      - 5431:5432
  redis:
    image: "redis:alpine"
    restart: always
  celery:
    build: .
    command: celery -A proj  worker -l INFO
    volumes:
      - .:/usr/projects/autopostingbot
    restart: always
    depends_on:
      - web
      - redis