version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: python app.py
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
  celery:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: celery -A proj  worker -l INFO
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/posting_data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=top1Dron
      - POSTGRES_DB=autopostingdb
  redis:
    image: "redis:alpine"

volumes:
  postgres_data: