version: '3.7'

services:
  web:
    build: ./
    command: python app.py
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  celery:
    build: ./
    command: celery -A proj  worker -l INFO
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - posting_postgres_data:/var/lib/postgresql/posting_data/
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pass12345
      - POSTGRES_DB=autoposting
  redis:
    image: "redis:alpine"

volumes:
  posting_postgres_data: